In [2]:
import autokeras as ak
import numpy as np
from keras.datasets import mnist
import tensorflow as tf

Using TensorFlow backend


2024-01-24 13:49:26.841451: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/treasures/AllProjects/Env/automl-merge/lib/python3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [6]:
import os
import glob
import numpy as np

train_dir = "/Users/treasures/Downloads/image_classification_training/data/train"
items = os.listdir(train_dir)
# 获取'文件夹'名称
folder_names = [item for item in items if os.path.isdir(os.path.join(train_dir, item))]

file_paths = []
labels = []
for folder_name in folder_names:
    files = glob.glob(os.path.join(train_dir, folder_name, '*'))
    file_paths.extend(files)
    labels.extend([folder_name] * len(files))

dataset = tf.data.Dataset.from_tensor_slices((file_paths, labels))

def load_image(file_path, label):
    image = tf.io.read_file(file_path)
    image = tf.image.decode_image(image, channels=3)
    return image, label

dataset = dataset.map(load_image)
# print(dataset)
x_train = []
y_train = []
for x, y in dataset:
    x_train.append(x)
    y_train.append(y)
# 将特征和标签转换为张量
x_train = np.asarray(tf.stack(x_train))
y_train = np.asarray(tf.stack(y_train))


ValueError: maximum supported dimension for an ndarray is 32, found 133

In [3]:
# (x_train, y_train), (x_test, y_test) = mnist.load_data()
# print(x_train)
# print(x_train.shape)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(60000, 28, 28)


In [4]:
input_node = ak.ImageInput()
output_node = ak.ResNetBlock(version="v2")(input_node)
output_node = ak.ClassificationHead()(output_node)

In [7]:
clf = ak.AutoModel(inputs=input_node, outputs=output_node, overwrite=True, max_trials=1, objective=None)
# clf.fit(x_train, y_train, epochs=1)
clf.fit(x=x_train, y=y_train, epochs=1)

ValueError: Expected x to have 1 arrays, but got 133

In [3]:
import os

print(os.path.pardir)
print()

..
../datasets/image-classification
